### PR TITLE
refactor(models)!: change SubaddressIndex to use subaddress::Index

### LINKED ISSUE #41: Replace `SubaddressIndex` with monero `Index`
Replace `monero_rpc::SubAddressIndex` with the native type `monero::cryptonote::subaddress::Index`.

### PR DESCRIPTION
**Pull request by LeoNero**
Closes #41 

https://github.com/monero-rs/monero-rs/pull/104 needs to be merged first

### CODE REVIEW

**Comment by h4sh3d** [comment]
`monero-rs` version [`0.17.1`](https://github.com/monero-rs/monero-rs/releases/tag/v0.17.1) has been release, this should now work!

**Comment by LeoNero** [comment]
@h4sh3d thank you! I'll update this PR

**Comment by LeoNero** [comment]
done

**Review by TheCharlatan — CHANGES_REQUESTED** [review]
I'd prefer if you use the imported Index wherever possible and also replace the currently defined tuples of indices with it. We are already using monero-rs as a user required library, so I'd prefer if we we were consistent. There is also no need to rename the Index to SubAddressIndex. This will be a breaking change to the lib.

**Comment by LeoNero** [comment]
@TheCharlatan  Done. I also used `subaddress::Index` instead of `Index` to make it easier to see it is not defined in this crate. I also changed any `account_index` and `address_indices` to use `u32` and `Vec<u32>` respectively, in order to make it use the same types `Index` uses.

**Comment by LeoNero** [comment]
btw I would only merge this PR after I add tests for all function on `lib.rs` in another PR

**Review by TheCharlatan — COMMENTED** [review]
Nicely done, and yes per your suggestion let's merge once the other PR is done. I like to put the onus of maintaining pull request merge order entirely on the author. Can you put this PR back in draft state as long as you are still working on its dependencies?

**Review by TheCharlatan — APPROVED** [review]
ACK

**Pull request merged**
